# Generated by Django 5.0.6 on 2024-06-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_booker'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='booker',
            table='booker',
        ),
    ]
