# Generated by Django 5.0.6 on 2024-06-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_booker_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
            ],
            options={
                'db_table': 'room',
            },
        ),
    ]
