# Generated by Django 5.0.6 on 2024-06-11 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_room'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table=None,
        ),
    ]
