# Generated by Django 5.0.6 on 2024-06-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_room_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
